config/routes.rb
Rails.application.routes.draw do

  resources :users
  match '/users/new', to: "users#new", via: "get"
  match '/friend/:id', to: "friendships#create", via: "post", as: "friendships"

  resources :sessions, only: [:index, :new, :create, :destroy]
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :chats

  resources :messages, only: [:new, :create]

  root 'chats#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :messages
end

app/models/chats_users.rb
class ChatsUsers < ActiveRecord::Base
	belongs_to :chat
	belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :chat;
	validates :content, presence: true, length: {minimum: 1}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :chats
	has_many :friendships
	has_many :friends, through: :friendships
	before_save {self.email = email.downcase}
	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	#validates :group, presence: true
	VALID_EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
		uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, length: {minimum: 6} 

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end
	
	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	private 
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)	
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  before_filter :check_sign_in

  private

  def check_sign_in
    if !signed_in?
     render 'sessions/index'
    end
  end


end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	include UsersHelper

	def index
		@chats = current_user.chats.order('updated_at DESC')
		@chat = @chats.first 
		@chat ||= Chat.new()
		@message = Message.new()
	end

	def show
		@chat = Chat.find(params[:id])
		@message = Message.new()
		respond_to do |format|
			format.js
		end
	end

	def new
		@chat = Chat.new
	end

	def create
		@chat = Chat.new()
		@chat.save
		@chat.users << current_user
		current_user.friends.each do |f|
			if params[f.name] == '1'
				@chat.users << f
			end
		end
		if params['random'] == '1'
			@chat.users += random_user_set params['amount'][0].to_i	
		end

		redirect_to root_url
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
  	user = User.find_by_name(params[:id])
  	if user != current_user && !(current_user.friends.include?(user))
  		@friendship = current_user.friendships.build(user_id: current_user.id, friend_id: user.id)
  		if @friendship.save
  			flash[:notice] = "Added friend"
  		else
    		flash[:notice] = "Couldn't add friend"
  		end
  	end
  	redirect_to request.referer
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create
		@message = Message.new(message_params)
		@chat = Chat.find(@message.chat_id)
		respond_to do |format|
			if @message.save
				format.js
			else
				flash[:notice] = @message.errors
				format.js
			end
		end
	end

	private

	def message_params
		params.require(:message).permit(:content, :chat_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_filter :check_sign_in, only: [:create, :index]

	def index
	end
	
	def destroy
		sign_out
		redirect_to root_url
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to chats_path
		else
			flash[:notice] = "Invalid password/email"
			render :index
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy]
  skip_before_filter :check_sign_in, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_name(params[:id])
    respond_to do |format|
      format.js
    end
    
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { 
          sign_in @user          
          redirect_to root_url, notice: 'User was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
  	if @user == current_user
	    respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to user_path(@user.name), notice: 'User was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
  	if @user == current_user
	    @user.destroy
	    respond_to do |format|
	      format.html { redirect_to users_url }
	      format.json { head :no_content }
	    end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :group, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper, UsersHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end
	
	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
	cookies.delete(:remember_token)
	self.current_user = nil
	end

	def signed_in?
		!current_user.nil?
	end

	def  current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def random_user_set (num)
		ids = User.ids
		users = []
		while users.count < num
			index = rand(0..ids.count-1)
			users << User.find(ids[index])
			ids.delete_at(index)
			break if ids.count == 0
		end
		return users
	end
end

app/views/chats/_messages.html.erb
<% chat.messages.each do |m| %>
	<p class="message">
	<%= m.content %>
	</p>
	<div class="separator-wide separator-increased-margins"></div>
<% end %>

app/views/chats/_new.html.erb
<div class="backdrop" id="new-chat-backdrop">

<strong> New Chat: </strong>

<%= form_for(@chat, class: "form") do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="centered">

  <div id="friends_div">

  <div id="friend-label">
  Add Friends:
  </div>

  <% current_user.friends.each do |f| %>
    <div class="separator"></div>
    <div class="click" onclick="reshade('friend_<%=f.name%>'); toggle('<%=f.name%>')">
    <div class="friend" id="friend_<%=f.name %>">
    <div class="hide">
    <%= check_box_tag(f.name) %>
    </div>
    <%= label_tag(f.name, f.name, class:"unbold friend-label")%><br> 
    </div>
    </div>
  <% end %>



  </div>
  


  <div class="separator-wide" id="chat-separator"></div>
  <%= check_box_tag(:random) %>
  <%= label_tag(:random, "Include random users?", class:"unbold inline") %><br> 
  <%= number_field(:amount, nil, in: 1..10, step: 1, id:"number") %><br>
  <%= f.submit "Create Chat", class:"btn btn-danger", id:"submit" %>

  </div>

<% end %>


</div>

app/views/chats/_show.html.erb
<strong>
<% @chat.users.each do |u| %>
	<%= link_to(u.name, user_path(u.name), remote: true, class:"dark-link") << ", " %>
<% end %>
</strong>
<div id="messages-container">
<div class="separator-wide separator-increased-margins"></div>
<div id="messages">
<%= render partial: "messages", locals: {chat: @chat} %>
</div>

<%= form_for(@message, remote: true, class:"form") do |f| %>

<%= f.text_field :content, class:"form-control inline", id: "message-field" %>
<%= f.hidden_field :chat_id, value: @chat.id %>
<%= f.submit class:"btn btn-danger pull-right inline"%>
<% end %>
</div>

app/views/chats/index.html.erb
<div class="backdrop">
<div class="title-bar"> <div class="subtitle"> Chats: </div> </div>
<div id="chats-list">
<div class="centered"> <strong>Your Chats:</strong></div>
<div class="separator-wide separator-increased-margins"></div>
<% @chats.each do |c| %>
	<%= link_to(chat_path(c.id), remote: true, class:"dark-link") do %>
	<div class="chat-link">
	<div class="chat-list-heading">
	Members:
	<% c.users[1..3].each do |f| %>
		<%= f.name << ", " %>
	<% end %>
	</div>
	<div class="chat-list-message">
	<% if c.messages.count != 0 %>
		<%= c.messages.first.content %>
	<% else %>
	Chat Empty...
	<% end %>

	</div>
	
	</div>
	
	<% end %>

	<div class="separator-wide separator-increased-margins"></div>
<% end %>
</div>
<div class="centered">
<div id="action_div">
<% if @chat.id %>
<%= render partial: "show" %>
<% else %>
<%= render partial: 'new'%>
<% end %>
</div>
</div>
</div>

app/views/chats/new.js.erb
$('#action_div').html('');
$('#action_div').html('<%= escape_javascript(render partial: "new") %>');

app/views/chats/show.js.erb
$('#action_div').html('<%= escape_javascript(render partial: 'chats/show') %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MaxProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" id="navbar" role="navigation">
<div class="navbar-content">

<div class="title ">
Anonymoose
</div>

<div id="links">
<% if signed_in? %>

<div class="glyphicon glyphicon-pencil"> </div>
<%= link_to "New Chat", new_chat_path, remote: true, class: "menu"%>

<div class="glyphicon glyphicon-list"> </div>
<%= link_to "Chats", chats_path, class: "menu"%>

<div class="glyphicon glyphicon-user"> </div>
<%= link_to "Yo, " << current_user.name, user_path(current_user.name), remote: true, class: "menu"%>

<div class="glyphicon glyphicon-log-out"> </div>
<%= link_to "Fuck this, I'm out", signout_path, method: :delete, class: "menu"%>

<% else %>

<div class="glyphicon glyphicon-log-in"> </div>
 <%=link_to "Information in, Bitches Out", sessions_path, class: "menu"%> 

<% end %>

</div>


</div>
</nav>

<div id="container">
<%= yield %>
</div>
<div id="footer">
</div>

</body>
</html>

app/views/messages/create.js.erb
$('#messages').html('<%= escape_javascript(render partial: "chats/messages", locals: { chat: @chat} ) %>')
$('#message-field').val('')
$('#messages').scrollTop(20);

app/views/users/_form.html.erb
<%= form_for(@user, class: "form") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, placeholder: "Email Address", class: "form-control squre" %>
  </div>
  <div class="form-group">
    <%=f.password_field :password, placeholder: "Password", class: "form-control square" %>
  </div>
  <div class="form-group">
    <%=f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control square" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/users/_show.html.erb
<p id="notice"><%= notice %></p>
<div class="user_profile_bar backdrop">

	<strong><%= @user.name %> </strong>

	<br>
	<% if @user == current_user %>
	<%= link_to 'Edit yo shit', edit_user_path(@user), class: "dark-link" %>
	<% else %>
	<% if signed_in? %>
	<%= link_to 'Friend this bitch', friendships_path(@user.name), class: "dark-link", method: "post" %>
	<% end %>
	<% end %>
	<br><strong>Friends:</strong><br>

	<div class="separator"></div>
	<% @user.friends.each do |f| %>
		<%= link_to f.name, user_path(f.name), class: "dark-link", remote: true %><br>
		<div class="separator"></div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Profile', user_path(@user.name) %> |
<%= link_to 'Back', root_url %>

app/views/users/new.html.erb
<h1>New User:</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/show.js.erb
$('#action_div').html('<%= escape_javascript(render partial: "show") %>');